version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    target-branch: "main"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      actions:
        patterns:
          - "*"
