import { invoke } from '@tauri-apps/api/core';
import { act, fireEvent,render,screen, waitFor } from '@testing-library/react';
import { beforeEach,describe,expect,it,vi } from 'vitest';
import { applyTheme } from '../../theme/theme-registry';
import { useTabsStore } from '../../stores/tabs-store';
import { useOverlayStore } from '../../stores/overlay-store';
import { clearTabRefreshRegistrationsForTests, registerTabRefresh } from '../../lib/tab-refresh';
import { WorkspaceTabStrip } from './WorkspaceTabStrip';

const now=Date.now();
const home={id:'native:home',family:'native' as const,kind:'home' as const,title:'Home',pinned:true,closable:false,createdAt:now,lastActivatedAt:now};
const longAccount={id:'github:profile',family:'browser' as const,kind:'profile' as const,title:'Account danyalahmed1995 with an extraordinarily long GitHub title',canonicalUrl:'https://github.com/danyalahmed1995',currentUrl:'https://github.com/danyalahmed1995',history:['https://github.com/danyalahmed1995'],historyIndex:0,lifecycle:'resident' as const,pinned:false,closable:true,createdAt:now,lastActivatedAt:now};

describe('workspace tab close controls',()=>{
  it('keeps the tab strip inside the workspace frame instead of creating a competing glass panel',()=>{render(<WorkspaceTabStrip/>);expect(screen.getByRole('tablist')).toHaveClass('workspace-tab-strip');expect(screen.getByRole('tablist')).not.toHaveClass('glass-panel');});
  beforeEach(()=>{applyTheme('dark-glass');clearTabRefreshRegistrationsForTests();useOverlayStore.setState({activeOverlayId:undefined});vi.mocked(invoke).mockClear();useTabsStore.setState({tabs:[home,{id:'native:long',family:'native',kind:'flow',title:'An extraordinarily long account simulator title that must truncate before close',pinned:false,closable:true,createdAt:now,lastActivatedAt:now}],activeTabId:'native:long'});});
  it('keeps a separately labelled close target beside a truncating title',()=>{render(<WorkspaceTabStrip/>);const close=screen.getByRole('button',{name:'Close An extraordinarily long account simulator title that must truncate before close'});expect(close).toBeInTheDocument();expect(close.closest('.workspace-tab')?.querySelector('.workspace-tab__title')).toHaveTextContent('An extraordinarily long');fireEvent.click(close);expect(useTabsStore.getState().tabs.map(tab=>tab.id)).toEqual(['native:home']);});
  it('supports middle-click close on the tab surface',()=>{render(<WorkspaceTabStrip/>);fireEvent(screen.getByRole('tab',{name:/An extraordinarily long/}),new MouseEvent('auxclick',{button:1,bubbles:true}));expect(useTabsStore.getState().tabs).toHaveLength(1);});
  it('renders a visible close control for the active Account browser tab',()=>{useTabsStore.setState({tabs:[home,longAccount],activeTabId:'github:profile'});render(<WorkspaceTabStrip/>);expect(screen.queryByRole('button',{name:'Close Home'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Close Account danyalahmed1995 with an extraordinarily long GitHub title'})).toBeInTheDocument();});
  it('keeps Account close controls available after switching to a light theme',()=>{useTabsStore.setState({tabs:[home,longAccount],activeTabId:'github:profile'});applyTheme('frosted-light');render(<WorkspaceTabStrip/>);const close=screen.getByRole('button',{name:'Close Account danyalahmed1995 with an extraordinarily long GitHub title'});expect(close).toBeVisible();expect(close.closest('.workspace-tab')?.querySelector('.workspace-tab__title')).toHaveTextContent('Account danyalahmed1995');});
  it('refreshes a browser tab by reloading the same webview tab',async()=>{useTabsStore.setState({tabs:[home,longAccount],activeTabId:'github:profile'});render(<WorkspaceTabStrip/>);fireEvent.contextMenu(screen.getByRole('tab',{name:/Account danyalahmed1995/}),{clientX:80,clientY:40});fireEvent.click(screen.getByRole('menuitem',{name:/Refresh tab/}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('browser_reload',{tabId:'github:profile'}));expect(useTabsStore.getState().tabs).toHaveLength(2);});
  it('refreshes a native tab through the registered page action',async()=>{const refresh=vi.fn();registerTabRefresh('native:long',{refresh});render(<WorkspaceTabStrip/>);fireEvent.contextMenu(screen.getByRole('tab',{name:/An extraordinarily long/}),{clientX:80,clientY:40});fireEvent.click(screen.getByRole('menuitem',{name:/Refresh tab/}));await waitFor(()=>expect(refresh).toHaveBeenCalledTimes(1));expect(invoke).not.toHaveBeenCalledWith('browser_reload',expect.anything());});
  it('dismisses the context menu on outside click without closing a tab',()=>{render(<WorkspaceTabStrip/>);fireEvent.contextMenu(screen.getByRole('tab',{name:/An extraordinarily long/}),{clientX:80,clientY:40});expect(screen.getByRole('menu')).toBeInTheDocument();fireEvent.pointerDown(document.body);expect(screen.queryByRole('menu')).not.toBeInTheDocument();expect(useTabsStore.getState().tabs.map(tab=>tab.id)).toEqual(['native:home','native:long']);});
  it('clicking another tab dismisses the menu and activates that tab',()=>{render(<WorkspaceTabStrip/>);fireEvent.contextMenu(screen.getByRole('tab',{name:/An extraordinarily long/}),{clientX:80,clientY:40});fireEvent.pointerDown(screen.getByRole('tab',{name:/Home/}));fireEvent.click(screen.getByRole('tab',{name:/Home/}));expect(screen.queryByRole('menu')).not.toBeInTheDocument();expect(useTabsStore.getState().activeTabId).toBe('native:home');});
  it('Escape dismisses the menu and returns focus to the originating tab',async()=>{render(<WorkspaceTabStrip/>);const tab=screen.getByRole('tab',{name:/An extraordinarily long/});fireEvent.contextMenu(tab,{clientX:80,clientY:40});fireEvent.keyDown(window,{key:'Escape'});expect(screen.queryByRole('menu')).not.toBeInTheDocument();await waitFor(()=>expect(tab).toHaveFocus());});
  it('window blur and other overlays dismiss the menu',()=>{render(<WorkspaceTabStrip/>);const tab=screen.getByRole('tab',{name:/An extraordinarily long/});fireEvent.contextMenu(tab,{clientX:80,clientY:40});fireEvent.blur(window);expect(screen.queryByRole('menu')).not.toBeInTheDocument();fireEvent.contextMenu(tab,{clientX:80,clientY:40});act(()=>useOverlayStore.getState().openOverlay('command-palette'));expect(screen.queryByRole('menu')).not.toBeInTheDocument();});
  it('keeps menu placement inside the viewport near edges',()=>{const width=window.innerWidth;const height=window.innerHeight;Object.defineProperty(window,'innerWidth',{value:180,configurable:true});Object.defineProperty(window,'innerHeight',{value:160,configurable:true});render(<WorkspaceTabStrip/>);fireEvent.contextMenu(screen.getByRole('tab',{name:/An extraordinarily long/}),{clientX:999,clientY:999});const menu=screen.getByRole('menu');expect(Number.parseFloat(menu.style.left)).toBeLessThanOrEqual(8);expect(Number.parseFloat(menu.style.top)).toBeLessThanOrEqual(8);Object.defineProperty(window,'innerWidth',{value:width,configurable:true});Object.defineProperty(window,'innerHeight',{value:height,configurable:true});});
});
