import { useEffect,useState } from 'react';
import { Maximize2,Minus,Plus,RotateCcw } from 'lucide-react';
import type { RepositoryFile } from '../../repository/repository-types';
import { createSafeImageUrl,MAX_IMAGE_PREVIEW_BYTES } from '../../repository/image-preview';

export function ImagePreview({file,mode,zoom,onMode,onZoom}:{file:RepositoryFile;mode:'fit'|'actual';zoom:number;onMode:(mode:'fit'|'actual')=>void;onZoom:(zoom:number)=>void}){
  const [source,setSource]=useState<string>();const [status,setStatus]=useState('Decoding image…');const [dimensions,setDimensions]=useState<{width:number;height:number}>();const [error,setError]=useState<string>();
  const byteSize=typeof file.byteSize==='number'&&Number.isFinite(file.byteSize)?file.byteSize:0;
  useEffect(()=>{let url:string|undefined;let current=true;Promise.resolve().then(()=>{if(!current)return;if(byteSize>MAX_IMAGE_PREVIEW_BYTES){setSource(undefined);setStatus('Preview limited');return;}setStatus('Decoding image…');setError(undefined);try{url=createSafeImageUrl(file);if(current){setSource(url);setStatus('Rendering preview…');}else{URL.revokeObjectURL(url);}}catch(cause){setError(String(cause));setStatus('Preview unavailable');}});return()=>{current=false;if(url)URL.revokeObjectURL(url);};},[byteSize,file]);
  if(byteSize>MAX_IMAGE_PREVIEW_BYTES)return <div className="repo-state"><strong>Oversized image preview limited</strong><span>{file.path} is {byteSize.toLocaleString()} bytes. The safe preview limit is {MAX_IMAGE_PREVIEW_BYTES.toLocaleString()} bytes.</span></div>;
  if(error)return <div className="repo-state repo-state--error"><strong>Image preview blocked</strong><span>{error}</span></div>;
  const bounded=(value:number)=>Math.max(.25,Math.min(4,Math.round(value*100)/100));
  return <div className="image-viewer"><div className="image-toolbar"><div role="group" aria-label="Image sizing"><button className={mode==='fit'?'is-active':''} onClick={()=>{onMode('fit');onZoom(1)}}><Maximize2 size={13}/>Fit</button><button className={mode==='actual'?'is-active':''} onClick={()=>{onMode('actual');onZoom(1)}}>Actual size</button></div><div role="group" aria-label="Image zoom"><button aria-label="Zoom out" onClick={()=>onZoom(bounded(zoom-.25))}><Minus size={13}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>onZoom(bounded(zoom+.25))}><Plus size={13}/></button><button onClick={()=>{onMode('fit');onZoom(1)}}><RotateCcw size={13}/>Reset</button></div><span>{dimensions?`${dimensions.width} × ${dimensions.height}`:'Dimensions pending'} · {file.mimeType??file.path.split('.').pop()?.toUpperCase()} · {byteSize.toLocaleString()} bytes · {status}</span></div><div className={`image-preview image-preview--${mode}`} onWheel={event=>{if(event.ctrlKey){event.preventDefault();onZoom(bounded(zoom+(event.deltaY<0?.1:-.1)));}}}>{source&&<img draggable={false} alt={file.path} src={source} onLoad={event=>{setDimensions({width:event.currentTarget.naturalWidth,height:event.currentTarget.naturalHeight});setStatus('Image ready')}} style={mode==='actual'&&dimensions?{width:dimensions.width*zoom,height:dimensions.height*zoom,maxWidth:'none',maxHeight:'none'}:{transform:`scale(${zoom})`}}/>}</div></div>;
}
