import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { ChevronRight, Copy, ExternalLink, FileCode2, FileSearch, GitBranch, RefreshCw, Search } from 'lucide-react';
import { useModeStore } from '../../stores/mode-store';
import { useTabsStore } from '../../stores/tabs-store';
import { classifyFile, languageForPath, normalizeTree, treeCacheKey, type RepositoryBranch, type RepositoryEntry, type RepositoryFile } from '../../repository/repository-types';
import { demoAllEntries, demoBranches, demoFile, demoTree } from '../../repository/demo-repository';
import { explorerStateFor, useExplorerStore } from '../../stores/explorer-store';
import { flatEntriesToRows, type TreeRow } from '../../repository/tree-model';
import { ImagePreview } from './ImagePreview';
import { RepositorySearchPanel } from './RepositorySearchPanel';
import { VirtualRepositoryTree, type VirtualTreeHandle } from './VirtualRepositoryTree';
import { scheduleDelayedStage } from '../../lib/loading-state';
import { Select } from '../ui/Select';
import { useTabRefresh } from '../../hooks/useTabRefresh';
import './RepositoryExplorer.css';
import './RepositorySearchPanel.css';

interface ExplorerProps { repository:string; initialRef?:string; initialPath?:string }
type TreeState=Record<string,RepositoryEntry[]>;
type SelectedKind='root'|'tree'|'blob';
const treeCache=new Map<string,RepositoryEntry[]>();

function mergeEntries(current:RepositoryEntry[],next:RepositoryEntry[]){const map=new Map(current.map(entry=>[entry.path,entry]));for(const entry of next)map.set(entry.path,entry);return[...map.values()]}
function normalizeRepositoryPath(path?:unknown){if(typeof path!=='string'||!path)return'';return path.replace(/\\/g,'/').split('/').filter(Boolean).map(part=>{try{return decodeURIComponent(part)}catch{return part}}).join('/')}
function ancestorsAndSelf(path:string){if(!path)return[];const parts=path.split('/').filter(Boolean);return parts.map((_,index)=>parts.slice(0,index+1).join('/'))}
function parentPath(path:string){return path.includes('/')?path.slice(0,path.lastIndexOf('/')):''}
function normalizeRepositoryFile(value:unknown,path:string):RepositoryFile|undefined{if(!value||typeof value!=='object')return;const record=value as Partial<RepositoryFile>;return{path:typeof record.path==='string'?record.path:path,text:typeof record.text==='string'||record.text===null?record.text:null,byteSize:typeof record.byteSize==='number'&&Number.isFinite(record.byteSize)?record.byteSize:typeof record.text==='string'?new TextEncoder().encode(record.text).byteLength:0,contentBase64:typeof record.contentBase64==='string'?record.contentBase64:undefined,mimeType:typeof record.mimeType==='string'?record.mimeType:undefined}}

export function RepositoryExplorer({repository,initialRef,initialPath}:ExplorerProps){
  const mode=useModeStore(state=>state.mode);const[owner,name]=repository.split('/');
  const initialKey=`${repository}@${initialRef??'main'}`;const initialPersisted=explorerStateFor(useExplorerStore.getState().states,initialKey);const initialSelectedPath=normalizeRepositoryPath(initialPath??initialPersisted.selectedPath);
  const[selectedRef,setSelectedRef]=useState(initialRef??'main');const[branches,setBranches]=useState<RepositoryBranch[]>([]);const[tree,setTree]=useState<TreeState>({});const[searchIndex,setSearchIndex]=useState<RepositoryEntry[]>(mode==='demo'?demoAllEntries():[]);const[expanded,setExpanded]=useState(new Set(initialPersisted.expanded));const[selectedPath,setSelectedPath]=useState(initialSelectedPath);const[selectedKind,setSelectedKind]=useState<SelectedKind>(initialSelectedPath?'blob':'root');const[file,setFile]=useState<RepositoryFile>();const[treeFilter,setTreeFilter]=useState(initialPersisted.search);const[fileQuery,setFileQuery]=useState('');const[error,setError]=useState<string>();const[focusedPath,setFocusedPath]=useState('');const[stage,setStage]=useState('Restoring view…');const[showFullSearch,setShowFullSearch]=useState(false);
  const request=useRef(0);const navigation=useRef(0);const generation=useRef(0);const loadingTimer=useRef<number|undefined>(undefined);const virtualTree=useRef<VirtualTreeHandle>(null);const states=useExplorerStore(state=>state.states);const updatePersisted=useExplorerStore(state=>state.update);const activeTabId=useTabsStore(state=>state.activeTabId);const persistKey=`${repository}@${selectedRef}`;const persisted=explorerStateFor(states,persistKey);
  const showStage=(value:string)=>{window.clearTimeout(loadingTimer.current);loadingTimer.current=scheduleDelayedStage(setStage,value)};const ready=()=>{window.clearTimeout(loadingTimer.current);setStage('Ready')};

  const loadTree=useCallback(async(path='',force=false)=>{const scope=generation.current;const key=treeCacheKey(repository,selectedRef,path);if(!force&&treeCache.has(key)){const cached=treeCache.get(key)!;setTree(value=>({...value,[key]:cached}));setSearchIndex(value=>mode==='demo'?value:mergeEntries(value,cached));return cached}showStage('Loading repository tree…');const entries=mode==='demo'?demoTree(path):(await invoke<{entries?:RepositoryEntry[]}>('get_repo_tree',{owner,name,expression:`${selectedRef}:${path}`}))?.entries??[];if(scope!==generation.current)return[];const normalized=normalizeTree(entries);treeCache.set(key,normalized);setTree(value=>({...value,[key]:normalized}));setSearchIndex(value=>mode==='demo'?value:mergeEntries(value,normalized));ready();return normalized},[mode,name,owner,repository,selectedRef]);

  useEffect(()=>{const scope=++generation.current;setStage('Opening repository…');setError(undefined);setTree({});setSearchIndex(mode==='demo'?demoAllEntries():[]);void(async()=>{try{let next=demoBranches;if(mode!=='demo'){const result=await invoke<Record<string,any>>('execute_graphql',{query:'query($owner:String!,$name:String!){repository(owner:$owner,name:$name){defaultBranchRef{name} refs(refPrefix:"refs/heads/",first:50,orderBy:{field:ALPHABETICAL,direction:ASC}){nodes{name}}}}',variables:{owner,name}});const repo=result?.data?.repository;if(!repo)throw new Error('Repository unavailable or deleted');next=(repo.refs?.nodes??[]).map((item:{name:string})=>({name:item.name,kind:'branch' as const,isDefault:item.name===repo.defaultBranchRef?.name}));if(!initialRef&&repo.defaultBranchRef?.name)setSelectedRef(repo.defaultBranchRef.name)}if(scope===generation.current)setBranches(next)}catch(cause){if(scope===generation.current)setError(readableError(cause))}finally{if(scope===generation.current)ready()}})();return()=>{generation.current++;window.clearTimeout(loadingTimer.current)}},[initialRef,mode,name,owner,repository]);
  useEffect(()=>{void loadTree().catch(cause=>setError(readableError(cause)))},[loadTree]);
  useEffect(()=>{const id=++request.current;if(!selectedPath||selectedKind!=='blob'){setFile(undefined);setError(undefined);ready();return}showStage(classifyFile(selectedPath,0,'')==='image'?'Fetching image…':'Fetching GitHub data…');setError(undefined);void(async()=>{try{const raw=mode==='demo'?demoFile(selectedPath):await invoke<RepositoryFile>('get_repo_file_content',{owner,name,expression:`${selectedRef}:${selectedPath}`,path:selectedPath});const next=normalizeRepositoryFile(raw,selectedPath);if(id===request.current){if(!next)throw new Error('File no longer exists');setFile(next);ready()}}catch(cause){if(id===request.current){setFile(undefined);setError(readableError(cause));ready()}}})();return()=>{request.current++}},[mode,name,owner,selectedKind,selectedPath,selectedRef]);
  useEffect(()=>{updatePersisted(persistKey,{expanded:[...expanded],selectedPath,search:treeFilter})},[expanded,persistKey,selectedPath,treeFilter,updatePersisted]);

  const lazyRows=useMemo(()=>{const rows:TreeRow[]=[];const walk=(path:string,depth:number)=>{for(const entry of tree[treeCacheKey(repository,selectedRef,path)]??[]){rows.push({...entry,depth});if(entry.type==='tree'&&expanded.has(entry.path))walk(entry.path,depth+1)}};walk('',1);return rows},[expanded,repository,selectedRef,tree]);
  const rows=treeFilter.trim()?flatEntriesToRows(searchIndex,treeFilter).map(row=>({...row,depth:row.depth+1})):lazyRows;
  const selectDirectory=useCallback(async(path:string)=>{const nextPath=normalizeRepositoryPath(path);const id=++navigation.current;request.current++;setSelectedPath(nextPath);setSelectedKind(nextPath?'tree':'root');setFocusedPath(nextPath);setFile(undefined);setFileQuery('');setError(undefined);setExpanded(value=>{const next=new Set(value);for(const ancestor of ancestorsAndSelf(nextPath))next.add(ancestor);return next});if(!nextPath){ready();return}try{for(const ancestor of ancestorsAndSelf(nextPath)){if(id!==navigation.current)return;await loadTree(ancestor)}if(id!==navigation.current)return;window.setTimeout(()=>virtualTree.current?.reveal(nextPath),0);ready()}catch(cause){if(id===navigation.current){setError(readableError(cause));ready()}}},[loadTree]);
  const selectFile=useCallback((path:string)=>{const nextPath=normalizeRepositoryPath(path);navigation.current++;setSelectedPath(nextPath);setSelectedKind(nextPath?'blob':'root');setFocusedPath(nextPath);setFileQuery('');setError(undefined);setExpanded(value=>{const next=new Set(value);for(const ancestor of ancestorsAndSelf(parentPath(nextPath)))next.add(ancestor);return next})},[]);
  const revealSearchResult=useCallback(async(path:string)=>{const nextPath=normalizeRepositoryPath(path);const id=++navigation.current;setShowFullSearch(false);setExpanded(value=>{const next=new Set(value);for(const ancestor of ancestorsAndSelf(parentPath(nextPath)))next.add(ancestor);return next});try{for(const ancestor of ['',...ancestorsAndSelf(parentPath(nextPath))]){if(id!==navigation.current)return;await loadTree(ancestor)}if(id!==navigation.current)return;selectFile(nextPath);window.setTimeout(()=>virtualTree.current?.reveal(nextPath),0)}catch(cause){if(id===navigation.current)setError(readableError(cause))}},[loadTree,selectFile]);
  const openEntry=async(entry:RepositoryEntry)=>{setFocusedPath(entry.path);if(entry.type==='tree'){setSelectedPath(entry.path);setSelectedKind('tree');setFile(undefined);setFileQuery('');setError(undefined);await loadTree(entry.path);setExpanded(value=>{const next=new Set(value);if(next.has(entry.path))next.delete(entry.path);else next.add(entry.path);for(const ancestor of ancestorsAndSelf(parentPath(entry.path)))next.add(ancestor);return next})}else selectFile(entry.path)};
  const selectRef=(reference:string)=>{generation.current++;navigation.current++;request.current++;setSelectedRef(reference);const next=explorerStateFor(useExplorerStore.getState().states,`${repository}@${reference}`);const nextPath=normalizeRepositoryPath(next.selectedPath);setExpanded(new Set(next.expanded));setSelectedPath(nextPath);setSelectedKind(nextPath?'blob':'root');setTreeFilter(next.search);setTree({});setSearchIndex(mode==='demo'?demoAllEntries():[]);setFile(undefined);setFileQuery('');setError(undefined)};
  const refresh=useCallback(async()=>{generation.current++;for(const key of[...treeCache.keys()])if(key.startsWith(`${repository}@${selectedRef}:`))treeCache.delete(key);setTree({});setSearchIndex(mode==='demo'?demoAllEntries():[]);setError(undefined);await loadTree('',true)},[loadTree,mode,repository,selectedRef,setError,setSearchIndex,setTree]);
  useTabRefresh(activeTabId,useMemo(()=>({label:'Refresh tab',refresh}),[refresh]));

  const keyNav=(event:React.KeyboardEvent)=>{const index=rows.findIndex(row=>row.path===focusedPath);const focusRow=(target:number)=>{event.preventDefault();const path=rows[target]?.path??'';setFocusedPath(path);virtualTree.current?.focus(path)};if(event.key==='Enter'&&rows[index]){event.preventDefault();void openEntry(rows[index]);return}if(event.key==='ArrowRight'&&rows[index]?.type==='tree'){event.preventDefault();if(!expanded.has(rows[index].path)&&!rows[index].forcedOpen){void openEntry(rows[index]);return}const child=rows.findIndex((row,rowIndex)=>rowIndex>index&&row.depth>rows[index].depth);if(child>=0)focusRow(child);return}if(event.key==='ArrowLeft'&&rows[index]){event.preventDefault();if(rows[index].type==='tree'&&expanded.has(rows[index].path)){void openEntry(rows[index]);return}const parent=parentPath(rows[index].path);const parentIndex=rows.findIndex(row=>row.path===parent);if(parentIndex>=0)focusRow(parentIndex);return}const target=event.key==='ArrowDown'?Math.min(rows.length-1,index+1):event.key==='ArrowUp'?Math.max(0,index-1):event.key==='Home'?0:event.key==='End'?rows.length-1:-1;if(target>=0)focusRow(target)};
  const githubUrl=`https://github.com/${repository}/${selectedKind==='blob'?'blob':'tree'}/${selectedRef}${selectedPath?`/${selectedPath.split('/').map(encodeURIComponent).join('/')}`:''}`;const openGithub=()=>useTabsStore.getState().openBrowserTab(`github:${repository}:${selectedRef}:${selectedPath||'root'}`,'repository',name,githubUrl,false,true);const kind=file?classifyFile(file.path,file.byteSize,file.text):undefined;const fileSize=file?.byteSize??0;const lines=file?.text?.split('\n')??[];const matches=fileQuery?lines.reduce<number[]>((acc,line,index)=>{if(line.toLowerCase().includes(fileQuery.toLowerCase()))acc.push(index+1);return acc},[]):[];const breadcrumbSegments=useMemo(()=>selectedPath.split('/').filter(Boolean).map((part,index,all)=>({part,path:all.slice(0,index+1).join('/'),kind:index===all.length-1?selectedKind:'tree' as SelectedKind})),[selectedKind,selectedPath]);

  return <div className="repo-explorer"><header className="repo-explorer__header"><div><span className="repo-explorer__eyebrow">Repository explorer</span><h1>{repository}</h1><p>Read-only native source browsing</p></div><div className="repo-explorer__actions"><button title="Search entire repository" aria-label="Search entire repository" onClick={()=>setShowFullSearch(true)}><FileSearch size={15}/></button><button title="Copy GitHub link" aria-label="Copy GitHub link" onClick={()=>navigator.clipboard.writeText(githubUrl)}><Copy size={15}/></button><button title="Refresh tree" aria-label="Refresh tree" onClick={()=>void refresh()}><RefreshCw size={15}/></button><button onClick={openGithub}><ExternalLink size={15}/>Open on GitHub</button></div></header>
    {showFullSearch&&<RepositorySearchPanel repository={repository} reference={selectedRef} demo={mode==='demo'} onClose={()=>setShowFullSearch(false)} onSelect={revealSearchResult}/>}<div className="repo-explorer__context"><label><GitBranch size={14}/><span className="sr-only">Branch or tag</span><Select ariaLabel="Branch or tag" searchable value={selectedRef} onChange={selectRef} options={branches.map(branch=>({value:branch.name,label:`${branch.kind==='tag'?'Tag: ':''}${branch.name}${branch.isDefault?' (default)':''}`}))}/></label><nav aria-label="File breadcrumb"><button aria-current={selectedKind==='root'?'page':undefined} onClick={()=>void selectDirectory('')}>{name}</button>{breadcrumbSegments.map(segment=><span key={segment.path}><ChevronRight size={12}/><button aria-current={segment.path===selectedPath?'page':undefined} onClick={()=>segment.kind==='blob'?selectFile(segment.path):void selectDirectory(segment.path)}>{segment.part}</button></span>)}</nav><span className="repo-explorer__state" aria-live="polite">{mode==='demo'?'Offline fixture':stage}</span></div>
    <div className="repo-explorer__body"><aside className="repo-tree" aria-label="Repository files"><label className="repo-search"><Search size={14}/><input aria-label="Filter loaded tree" value={treeFilter} onChange={event=>setTreeFilter(event.target.value)} placeholder="Filter loaded tree"/></label><button className="repo-tree__full-search" onClick={()=>setShowFullSearch(true)}><FileSearch size={13}/>Search entire repository</button><div className="repo-tree__section-label">TREE</div><VirtualRepositoryTree ref={virtualTree} repository={repository} rows={rows} expanded={expanded} selectedPath={selectedPath} selectedRoot={selectedKind==='root'} focusedPath={focusedPath} query={treeFilter} initialScrollTop={persisted.scrollTop} onRoot={()=>void selectDirectory('')} onOpen={entry=>void openEntry(entry)} onFocus={setFocusedPath} onKeyDown={keyNav} onScroll={scrollTop=>updatePersisted(persistKey,{scrollTop})}/></aside>
      <main className="file-preview"><header><div><FileCode2 size={16}/><strong>{selectedPath||'Repository root'}</strong>{file&&<span>{languageForPath(file.path)} · {fileSize.toLocaleString()} bytes</span>}</div>{file&&kind!=='image'&&kind!=='large'&&<label className="repo-search"><Search size={14}/><input aria-label="Search in file" value={fileQuery} onChange={event=>setFileQuery(event.target.value)} placeholder="Search in file"/></label>}</header><div className="file-preview__content">{error&&<div className="repo-state repo-state--error"><strong>Unable to load this content</strong><span>{error}</span><button onClick={()=>void selectDirectory(parentPath(selectedPath))}>Retry from parent directory</button></div>}{!file&&!error&&<div className="repo-state"><strong>{selectedKind==='root'?'Repository root selected':selectedKind==='tree'?'Directory selected':stage}</strong><span>{selectedKind==='blob'?'Waiting for selected content.':'Choose a file from the tree to preview it.'}</span></div>}{file&&kind==='large'&&<div className="repo-state repo-state--guard"><strong>Large file preview limited</strong><span>This {fileSize.toLocaleString()} byte file exceeds the 1 MB source preview budget.</span><button onClick={openGithub}>Open on GitHub</button></div>}{file&&kind==='binary'&&<div className="repo-state"><strong>Unsupported binary file</strong><span>Snow Devil does not execute or decode this file type.</span><button onClick={openGithub}>Open on GitHub</button></div>}{file&&kind==='image'&&<ImagePreview file={file} mode={persisted.imageMode} zoom={persisted.zoom} onMode={imageMode=>updatePersisted(persistKey,{imageMode})} onZoom={zoom=>updatePersisted(persistKey,{zoom})}/>} {file&&kind==='markdown'&&<article className="markdown-preview"><ReactMarkdown remarkPlugins={[remarkGfm]}>{file.text??''}</ReactMarkdown></article>}{file&&kind==='text'&&<div className="code-preview" role="region" aria-label={`${selectedPath} source`}><table><tbody>{lines.map((line,index)=><tr key={index} className={matches.includes(index+1)?'is-match':''}><td>{index+1}</td><td><code>{line||' '}</code></td></tr>)}</tbody></table></div>}</div></main></div></div>;
}

function readableError(cause:unknown){const value=String(cause);if(value.includes('rate'))return'GitHub rate limit reached. Cached content remains available; retry later.';if(value.includes('401')||value.includes('auth'))return'Authentication expired. Reconnect your GitHub account.';if(value.includes('404')||value.includes('null'))return'This repository, branch, or file no longer exists.';if(value.includes('fetch')||value.includes('network')||value.includes('timeout'))return'GitHub is currently unreachable. Cached content remains available where possible.';return value.replace(/^Error:\s*/,'')}
