import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';
import { ChevronDown,ChevronRight,Copy,ExternalLink,FileCode2,GitBranch,RefreshCw,Search } from 'lucide-react';
import { useModeStore } from '../../stores/mode-store';import { useTabsStore } from '../../stores/tabs-store';
import { classifyFile,languageForPath,normalizeTree,treeCacheKey,type RepositoryBranch,type RepositoryEntry,type RepositoryFile } from '../../repository/repository-types';
import { demoAllEntries,demoBranches,demoFile,demoTree } from '../../repository/demo-repository';
import { explorerStateFor,useExplorerStore } from '../../stores/explorer-store';import { flatEntriesToRows,type TreeRow } from '../../repository/tree-model';
import { TreeFileIcon } from './TreeFileIcon';import { ImagePreview } from './ImagePreview';import './RepositoryExplorer.css';
import { scheduleDelayedStage } from '../../lib/loading-state';

interface ExplorerProps{repository:string;initialRef?:string;initialPath?:string}type TreeState=Record<string,RepositoryEntry[]>;
const treeCache=new Map<string,RepositoryEntry[]>();

export function RepositoryExplorer({repository,initialRef,initialPath}:ExplorerProps){
  const mode=useModeStore(s=>s.mode);const[owner,name]=repository.split('/');const initialKey=`${repository}@${initialRef??'main'}`;const initialPersisted=explorerStateFor(useExplorerStore.getState().states,initialKey);
  const[selectedRef,setSelectedRef]=useState(initialRef??'main');const[branches,setBranches]=useState<RepositoryBranch[]>([]);const[tree,setTree]=useState<TreeState>({});const[searchIndex,setSearchIndex]=useState<RepositoryEntry[]>(mode==='demo'?demoAllEntries():[]);
  const[expanded,setExpanded]=useState<Set<string>>(new Set(initialPersisted.expanded));const[selectedPath,setSelectedPath]=useState(initialPath??initialPersisted.selectedPath);const[file,setFile]=useState<RepositoryFile>();const[treeFilter,setTreeFilter]=useState(initialPersisted.search);const[fileQuery,setFileQuery]=useState('');const[error,setError]=useState<string>();const[focusedPath,setFocusedPath]=useState('');const[stage,setStage]=useState('Restoring view…');
  const request=useRef(0);const generation=useRef(0);const treeRowsRef=useRef<HTMLDivElement>(null);const loadingTimer=useRef<number|undefined>(undefined);const states=useExplorerStore(s=>s.states);const updatePersisted=useExplorerStore(s=>s.update);const persistKey=`${repository}@${selectedRef}`;const persisted=explorerStateFor(states,persistKey);
  const showStage=(value:string)=>{window.clearTimeout(loadingTimer.current);loadingTimer.current=scheduleDelayedStage(setStage,value)};const ready=()=>{window.clearTimeout(loadingTimer.current);setStage('Ready')};

  const loadTree=useCallback(async(path='',force=false)=>{const scope=generation.current;const key=treeCacheKey(repository,selectedRef,path);if(!force&&treeCache.has(key)){const cached=treeCache.get(key)!;setTree(value=>({...value,[key]:cached}));return cached;}showStage('Loading repository tree…');const entries=mode==='demo'?demoTree(path):((await invoke<{entries?:RepositoryEntry[]}>('get_repo_tree',{owner,name,expression:`${selectedRef}:${path}`}))?.entries??[]);if(scope!==generation.current)return[];const normalized=normalizeTree(entries);treeCache.set(key,normalized);setTree(value=>({...value,[key]:normalized}));ready();return normalized;},[mode,name,owner,repository,selectedRef]);

  useEffect(()=>{const scope=++generation.current;setStage('Opening repository…');setError(undefined);setTree({});setSearchIndex(mode==='demo'?demoAllEntries():[]);(async()=>{try{let next=demoBranches;if(mode!=='demo'){const result=await invoke<any>('execute_graphql',{query:'query($owner:String!,$name:String!){repository(owner:$owner,name:$name){defaultBranchRef{name} refs(refPrefix:"refs/heads/",first:50,orderBy:{field:ALPHABETICAL,direction:ASC}){nodes{name}}}}',variables:{owner,name}});const repo=result?.data?.repository;if(!repo)throw new Error('Repository unavailable or deleted');next=(repo.refs?.nodes??[]).map((item:{name:string})=>({name:item.name,kind:'branch',isDefault:item.name===repo.defaultBranchRef?.name}));if(!initialRef&&repo.defaultBranchRef?.name)setSelectedRef(repo.defaultBranchRef.name);}if(scope===generation.current)setBranches(next);}catch(cause){if(scope===generation.current)setError(readableError(cause));}finally{if(scope===generation.current)ready();}})();return()=>{generation.current++;window.clearTimeout(loadingTimer.current);};},[initialRef,mode,name,owner,repository]);
  useEffect(()=>{loadTree().catch(cause=>setError(readableError(cause)));},[loadTree]);
  useEffect(()=>{if(!treeFilter.trim()||mode==='demo')return;const scope=generation.current;const timer=window.setTimeout(async()=>{try{showStage('Searching repository paths…');const result=await invoke<any>('execute_rest',{endpoint:`/repos/${owner}/${name}/git/trees/${encodeURIComponent(selectedRef)}?recursive=1`});if(scope!==generation.current)return;setSearchIndex((result?.tree??[]).filter((item:any)=>item.type==='tree'||item.type==='blob').map((item:any)=>({name:item.path.split('/').pop(),path:item.path,type:item.type})));ready();}catch(cause){if(scope===generation.current)setError(readableError(cause));}},220);return()=>clearTimeout(timer);},[mode,name,owner,selectedRef,treeFilter]);
  useEffect(()=>{const id=++request.current;if(!selectedPath){setFile(undefined);return;}showStage(classifyFile(selectedPath,0,'')==='image'?'Fetching image…':'Fetching GitHub data…');setError(undefined);(async()=>{try{const next=mode==='demo'?demoFile(selectedPath):await invoke<RepositoryFile>('get_repo_file_content',{owner,name,expression:`${selectedRef}:${selectedPath}`,path:selectedPath});if(id===request.current){if(!next)throw new Error('File no longer exists');setFile(next);ready();}}catch(cause){if(id===request.current){setFile(undefined);setError(readableError(cause));ready();}}})();return()=>{request.current++;};},[mode,name,owner,selectedPath,selectedRef]);
  useEffect(()=>{updatePersisted(persistKey,{expanded:[...expanded],selectedPath,search:treeFilter});},[expanded,persistKey,selectedPath,treeFilter,updatePersisted]);
  useEffect(()=>{const element=treeRowsRef.current;if(element)element.scrollTop=persisted.scrollTop;},[persistKey]);

  const lazyRows=useMemo(()=>{const rows:TreeRow[]=[];const walk=(path:string,depth:number)=>{for(const entry of tree[treeCacheKey(repository,selectedRef,path)]??[]){rows.push({...entry,depth});if(entry.type==='tree'&&expanded.has(entry.path))walk(entry.path,depth+1);}};walk('',1);return rows;},[expanded,repository,selectedRef,tree]);
  const rows=treeFilter.trim()?flatEntriesToRows(searchIndex,treeFilter).map(row=>({...row,depth:row.depth+1})):lazyRows;
  const openEntry=async(entry:RepositoryEntry)=>{setFocusedPath(entry.path);if(entry.type==='tree'){await loadTree(entry.path);setExpanded(value=>{const next=new Set(value);if(next.has(entry.path))next.delete(entry.path);else next.add(entry.path);return next;});}else setSelectedPath(entry.path);};
  const selectRef=(ref:string)=>{generation.current++;request.current++;setSelectedRef(ref);const next=explorerStateFor(useExplorerStore.getState().states,`${repository}@${ref}`);setExpanded(new Set(next.expanded));setSelectedPath(next.selectedPath);setTreeFilter(next.search);setTree({});setFile(undefined);setError(undefined);};
  const refresh=async()=>{generation.current++;for(const key of [...treeCache.keys()])if(key.startsWith(`${repository}@${selectedRef}:`))treeCache.delete(key);setTree({});setSearchIndex(mode==='demo'?demoAllEntries():[]);setError(undefined);await loadTree('',true);};
  const githubUrl=`https://github.com/${repository}/${selectedPath?'blob':'tree'}/${selectedRef}${selectedPath?`/${selectedPath}`:''}`;
  const openGithub=()=>useTabsStore.getState().openBrowserTab(`github:${repository}:${selectedRef}:${selectedPath||'root'}`,'repository',name,githubUrl,false,true);
  const kind=file?classifyFile(file.path,file.byteSize,file.text):undefined;const lines=file?.text?.split('\n')??[];const matches=fileQuery?lines.reduce<number[]>((acc,line,index)=>{if(line.toLowerCase().includes(fileQuery.toLowerCase()))acc.push(index+1);return acc;},[]):[];
  const keyNav=(event:React.KeyboardEvent)=>{
    const index=rows.findIndex(row=>row.path===focusedPath);
    if(event.key==='ArrowRight'&&rows[index]?.type==='tree'&&!expanded.has(rows[index].path)){void openEntry(rows[index]);return;}
    if(event.key==='ArrowLeft'&&rows[index]?.type==='tree'&&expanded.has(rows[index].path)){void openEntry(rows[index]);return;}
    const target=event.key==='ArrowDown'?Math.min(rows.length-1,index+1):event.key==='ArrowUp'?Math.max(0,index-1):event.key==='Home'?0:event.key==='End'?rows.length-1:-1;
    if(target<0)return;
    event.preventDefault();setFocusedPath(rows[target]?.path??'');document.querySelector<HTMLElement>(`[data-tree-path="${CSS.escape(rows[target]?.path??'')}"]`)?.focus();
  };

  return <div className="repo-explorer"><header className="repo-explorer__header"><div><span className="repo-explorer__eyebrow">Repository explorer</span><h1>{repository}</h1><p>Read-only native source browsing</p></div><div className="repo-explorer__actions"><button title="Copy GitHub link" aria-label="Copy GitHub link" onClick={()=>navigator.clipboard.writeText(githubUrl)}><Copy size={15}/></button><button title="Refresh tree" aria-label="Refresh tree" onClick={()=>void refresh()}><RefreshCw size={15}/></button><button onClick={openGithub}><ExternalLink size={15}/>Open on GitHub</button></div></header>
    <div className="repo-explorer__context"><label><GitBranch size={14}/><span className="sr-only">Branch or tag</span><select value={selectedRef} onChange={event=>selectRef(event.target.value)}>{branches.map(branch=><option key={`${branch.kind}:${branch.name}`} value={branch.name}>{branch.kind==='tag'?'Tag: ':''}{branch.name}{branch.isDefault?' (default)':''}</option>)}</select></label><nav aria-label="File breadcrumb"><button onClick={()=>setSelectedPath('')}>{name}</button>{selectedPath.split('/').filter(Boolean).map((part,index,all)=><span key={`${part}-${index}`}><ChevronRight size={12}/><button onClick={()=>setSelectedPath(all.slice(0,index+1).join('/'))}>{part}</button></span>)}</nav><span className="repo-explorer__state" aria-live="polite">{mode==='demo'?'Offline fixture':stage}</span></div>
    <div className="repo-explorer__body"><aside className="repo-tree" aria-label="Repository files"><label className="repo-search"><Search size={14}/><input aria-label="Filter files" value={treeFilter} onChange={event=>setTreeFilter(event.target.value)} placeholder="Filter files and folders"/></label><div role="tree" aria-label={`${repository} file tree`} className="repo-tree__rows" ref={treeRowsRef} onKeyDown={keyNav} onScroll={event=>updatePersisted(persistKey,{scrollTop:event.currentTarget.scrollTop})}><button role="treeitem" aria-expanded="true" aria-level={1} className="repo-tree__root"><ChevronDown size={12}/><TreeFileIcon path={repository} type="tree" open/><span>{repository}</span></button>{rows.map(entry=><button role="treeitem" aria-level={entry.depth+1} aria-expanded={entry.type==='tree'?(entry.forcedOpen||expanded.has(entry.path)):undefined} aria-selected={entry.path===selectedPath} data-tree-path={entry.path} className={`${entry.path===selectedPath?'is-selected ':''}${entry.path===focusedPath?'is-focused ':''}${entry.matched?'is-match':''}`} style={{paddingLeft:10+entry.depth*16}} key={entry.path} onFocus={()=>setFocusedPath(entry.path)} onClick={()=>void openEntry(entry)} title={entry.path}>{entry.type==='tree'?(entry.forcedOpen||expanded.has(entry.path)?<ChevronDown className="tree-chevron" size={12}/>:<ChevronRight className="tree-chevron" size={12}/>):<span className="tree-chevron"/>}<TreeFileIcon path={entry.path} type={entry.type} open={entry.type==='tree'&&(entry.forcedOpen||expanded.has(entry.path))}/><Highlighted value={entry.name} query={treeFilter}/></button>)}</div></aside>
      <main className="file-preview"><header><div><FileCode2 size={16}/><strong>{selectedPath||'Repository root'}</strong>{file&&<span>{languageForPath(file.path)} · {file.byteSize.toLocaleString()} bytes</span>}</div>{file&&kind!=='image'&&<label className="repo-search"><Search size={14}/><input aria-label="Search in file" value={fileQuery} onChange={event=>setFileQuery(event.target.value)} placeholder="Search in file"/></label>}</header>{error&&<div className="repo-state repo-state--error"><strong>Unable to load this content</strong><span>{error}</span><button onClick={()=>setSelectedPath('')}>Return to repository root</button></div>}{!file&&!error&&<div className="repo-state"><strong>{stage}</strong><span>{selectedPath?'Waiting for selected content.':'Choose a file from the repository tree.'}</span></div>}{file&&kind==='large'&&<div className="repo-state"><strong>Large file preview limited</strong><span>This {file.byteSize.toLocaleString()} byte file exceeds the 1 MB source preview budget.</span><button onClick={openGithub}>Open on GitHub</button></div>}{file&&kind==='binary'&&<div className="repo-state"><strong>Unsupported binary file</strong><span>Snow Devil does not execute or decode this file type.</span><button onClick={openGithub}>Open on GitHub</button></div>}{file&&kind==='image'&&<ImagePreview file={file} mode={persisted.imageMode} zoom={persisted.zoom} onMode={imageMode=>updatePersisted(persistKey,{imageMode})} onZoom={zoom=>updatePersisted(persistKey,{zoom})}/>} {file&&kind==='markdown'&&<article className="markdown-preview"><ReactMarkdown remarkPlugins={[remarkGfm]}>{file.text??''}</ReactMarkdown></article>}{file&&kind==='text'&&<div className="code-preview" role="region" aria-label={`${selectedPath} source`}><table><tbody>{lines.map((line,index)=><tr key={index} className={matches.includes(index+1)?'is-match':''}><td>{index+1}</td><td><code>{line||' '}</code></td></tr>)}</tbody></table></div>}</main></div></div>;
}
function Highlighted({value,query}:{value:string;query:string}){const index=value.toLowerCase().indexOf(query.trim().toLowerCase());if(index<0||!query.trim())return <span>{value}</span>;return <span>{value.slice(0,index)}<mark>{value.slice(index,index+query.trim().length)}</mark>{value.slice(index+query.trim().length)}</span>}
function readableError(cause:unknown){const value=String(cause);if(value.includes('rate'))return'GitHub rate limit reached. Cached content remains available; retry later.';if(value.includes('401')||value.includes('auth'))return'Authentication expired. Reconnect your GitHub account.';if(value.includes('404')||value.includes('null'))return'This repository, branch, or file no longer exists.';if(value.includes('fetch')||value.includes('network')||value.includes('timeout'))return'GitHub is currently unreachable. Cached content remains available where possible.';return value.replace(/^Error:\s*/,'');}
