import {
  BadgeCheck,
  Binary,
  BookOpen,
  Box,
  Boxes,
  Braces,
  Coffee,
  Component,
  File,
  FileArchive,
  FileCode2,
  FileCog,
  FileImage,
  FileJson,
  FileKey2,
  FileText,
  Folder,
  FolderCode,
  FolderGit2,
  FolderOpen,
  Globe2,
  Hash,
  Image,
  Package,
  Palette,
  ScrollText,
  Settings,
  Terminal,
} from 'lucide-react';
import { resolveRepositoryTreeIcon, type RepositoryTreeIconKind } from '../../repository/repository-tree-icons';

export function TreeFileIcon({path,type,open=false}:{path:string;type:'tree'|'blob';open?:boolean}){
  const descriptor=resolveRepositoryTreeIcon(path,type,open);const Icon=ICON_COMPONENTS[descriptor.kind]??File;
  return <span className={`repo-tree-icon repo-tree-icon--${descriptor.kind}`} data-tree-icon={descriptor.kind} data-tooltip={descriptor.label} aria-hidden="true"><Icon size={15}/></span>;
}

const ICON_COMPONENTS: Record<RepositoryTreeIconKind, typeof File> = {
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-github": FolderGit2,
  "folder-source": FolderCode,
  "folder-public": Globe2,
  "folder-docs": BookOpen,
  "folder-scripts": Terminal,
  "folder-tests": BadgeCheck,
  "folder-assets": Image,
  "folder-config": Settings,
  "folder-build": Boxes,
  "folder-examples": Box,
  "folder-packages": Package,
  "folder-components": Component,
  "folder-styles": Palette,
  "file-markdown": FileText,
  "file-json": FileJson,
  "file-yaml": Braces,
  "file-typescript": FileCode2,
  "file-javascript": FileCode2,
  "file-rust": FileCode2,
  "file-html": FileCode2,
  "file-style": Palette,
  "file-shell": Terminal,
  "file-powershell": Terminal,
  "file-python": FileCode2,
  "file-cpp": FileCode2,
  "file-csharp": Hash,
  "file-java": Coffee,
  "file-swift": FileCode2,
  "file-image": FileImage,
  "file-media": Binary,
  "file-package": Package,
  "file-lock": FileKey2,
  "file-git": Hash,
  "file-env": FileCog,
  "file-license": ScrollText,
  "file-readme": BookOpen,
  "file-binary": FileArchive,
  "file-generic": File,
};
