import { AlertTriangle, Boxes, FileQuestion, GitBranch, Network, RefreshCw, ShieldCheck, Users } from 'lucide-react';
import type { ArchitectureSnapshot } from '../../architecture/types';
import './RepositoryArchitectureView.css';

export function RepositoryArchitectureView({ snapshot, loading, error, onRefresh, onSelect }: { snapshot?: ArchitectureSnapshot; loading: boolean; error?: string; onRefresh: () => void; onSelect: (componentId: string) => void }) {
  if (loading && !snapshot) return <div className="repository-architecture-state"><Network size={24}/><strong>Building component map</strong><span>Fetching the exact repository tree, then discovering boundaries, dependencies, and ownership.</span></div>;
  if (error && !snapshot) return <div className="repository-architecture-state repository-architecture-state--error"><AlertTriangle size={24}/><strong>Architecture analysis unavailable</strong><span>{error}</span><button onClick={onRefresh}><RefreshCw size={13}/>Retry</button></div>;
  if (!snapshot) return null;
  const mappedPercent = snapshot.evidenceSummary.totalFiles ? Math.round(snapshot.evidenceSummary.mappedFiles / snapshot.evidenceSummary.totalFiles * 100) : 0;
  const owners = snapshot.components.filter(component => component.owners.length).length;
  return <div className="repository-architecture">
    <header><div><span>Repository Architecture</span><h2>Component Index</h2><p>Deterministic repository model at {snapshot.baseCommitSha.slice(0, 12)}</p></div><button onClick={onRefresh}><RefreshCw size={13}/>Refresh architecture</button></header>
    <section className="repository-architecture__metrics"><article><Boxes/><span>Components<strong>{snapshot.components.length}</strong></span></article><article><GitBranch/><span>Dependencies<strong>{snapshot.dependencies.length}</strong></span></article><article><ShieldCheck/><span>Mapping coverage<strong>{mappedPercent}%</strong></span></article><article><Users/><span>Owned components<strong>{owners}</strong></span></article><article><FileQuestion/><span>Unmapped files<strong>{snapshot.unmappedFiles.length}</strong></span></article></section>
    {snapshot.warnings.length > 0 && <section className="repository-architecture__warnings">{snapshot.warnings.map(warning => <p key={`${warning.code}:${warning.message}`}><AlertTriangle size={12}/>{warning.message}</p>)}</section>}
    <main><section className="repository-architecture__components"><header><h3>Components</h3><span>{snapshot.status} · analyzed {new Date(snapshot.generatedAt).toLocaleString()}</span></header>{snapshot.components.map(component => <button key={component.id} onClick={() => onSelect(component.id)}><span className="repository-component-icon"><Boxes size={13}/></span><span><strong>{component.name}</strong><small>{component.kind} · {component.rootPaths.join(', ')}</small></span><em>{snapshot.files.filter(file => file.componentId === component.id).length} files</em><small>{component.confidence.level}</small></button>)}</section>
      <section className="repository-architecture__map"><header><h3>Dependency Map</h3><span>Bounded component relationships</span></header><div>{snapshot.components.slice(0, 16).map(component => { const outgoing = snapshot.dependencies.filter(edge => edge.fromComponentId === component.id); return <button key={component.id} onClick={() => onSelect(component.id)}><span><strong>{component.name}</strong><small>{component.kind}</small></span><em>{outgoing.length} outgoing</em></button>})}{snapshot.components.length > 16 && <p>+{snapshot.components.length - 16} more components</p>}</div><footer>{snapshot.dependencies.slice(0, 12).map(edge => <p key={`${edge.fromComponentId}:${edge.toComponentId}:${edge.kind}`}><GitBranch size={11}/>{snapshot.components.find(component => component.id === edge.fromComponentId)?.name} → {snapshot.components.find(component => component.id === edge.toComponentId)?.name}<em>{edge.kind}</em></p>)}{!snapshot.dependencies.length && <p>No cross-component dependency evidence was found.</p>}</footer></section></main>
  </div>;
}
