import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { ChevronDown, Eye, EyeOff, FileImage, GitCompare } from 'lucide-react';
import { collapseUnchanged, isWhitespaceOnlyChange, syntaxParts, type DiffFile, type DiffLine } from '../../diff/diff-utils';
import type { RepositoryFile } from '../../repository/repository-types';
import { createSafeImageUrl } from '../../repository/image-preview';

const IMAGE = /\.(png|jpe?g|webp|svg)$/i;
export const CHUNK = 1600;

export interface DiffData {
  baseRefName?: string;
  headRefName?: string;
  diffTruncated?: boolean;
}

export function DiffFileView({file,layout,query,ignoreWhitespace,expandedContext,renderLimit,data,repository,mode,viewed,onToggleViewed,onExpandContext,onRenderMore,onOpenOriginal}:{file:DiffFile;layout:'unified'|'split';query:string;ignoreWhitespace:boolean;expandedContext:boolean;renderLimit:number;data:DiffData;repository:string;mode:'live'|'demo';viewed:boolean;onToggleViewed:()=>void;onExpandContext:()=>void;onRenderMore:()=>void;onOpenOriginal:()=>void}){
  let lines=collapseUnchanged(file.lines,expandedContext);if(ignoreWhitespace)lines=lines.filter((line,index)=>!isWhitespaceOnlyChange(line,lines[index+(line.kind==='remove'?1:-1)]));const limited=lines.slice(0,renderLimit);const image=file.binary&&IMAGE.test(file.newPath);
  return <section className="diff-file"><header><span><strong>{file.newPath}</strong>{file.status!=='modified'&&<em>{file.status}</em>}{file.similarity!=null&&<em>{file.similarity}% similar</em>}{file.generated&&<em>generated</em>}{file.vendored&&<em>vendored</em>}</span><div><button onClick={onOpenOriginal}>Open source</button><button onClick={onToggleViewed}>{viewed?<EyeOff size={12}/>:<Eye size={12}/>} {viewed?'Unview':'Viewed'}</button><b>+{file.additions}</b><i>-{file.deletions}</i></div></header>{image?<ImageDiff file={file} data={data} repository={repository} mode={mode}/>:file.binary?<div className="diff-state"><strong>Binary file changed</strong><span>The patch does not contain binary bytes. Open the changed file or GitHub for details.</span></div>:<>{layout==='unified'?<table className="diff-unified"><tbody>{limited.map((line,index)=><DiffRow key={index} line={line} path={file.newPath} query={query} onExpand={onExpandContext}/>)}</tbody></table>:<table className="diff-split"><tbody>{splitRows(limited).map((row,index)=><tr key={index}><td className={row.left?.kind?`is-${row.left.kind}`:''}><span>{row.left?.oldNumber??''}</span><code><HighlightedCode line={row.left} path={file.oldPath} query={query}/></code></td><td className={row.right?.kind?`is-${row.right.kind}`:''}><span>{row.right?.newNumber??''}</span><code><HighlightedCode line={row.right} path={file.newPath} query={query}/></code></td></tr>)}</tbody></table>}{limited.some(line=>line.collapsedCount)&&<button className="diff-expand-context" onClick={onExpandContext}><ChevronDown size={13}/>Expand unchanged context</button>}{lines.length>limited.length&&<button className="diff-load-more" onClick={onRenderMore}>Render {Math.min(CHUNK,lines.length-limited.length).toLocaleString()} more lines</button>}{data.diffTruncated&&<div className="diff-warning">GitHub truncated this patch. Open on GitHub for the complete change.</div>}</>}</section>;
}

export function DiffRow({line,path,query,onExpand}:{line:DiffLine;path:string;query:string;onExpand:()=>void}){return <tr className={`is-${line.kind}`}><td>{line.oldNumber??''}</td><td>{line.newNumber??''}</td><td><code>{line.collapsedCount?<button className="diff-collapsed" onClick={onExpand}>{line.text}</button>:<><span>{line.kind==='add'?'+':line.kind==='remove'?'-':' '}</span><HighlightedCode line={line} path={path} query={query}/></>}</code></td></tr>}

export function HighlightedCode({line,path,query}:{line?:DiffLine;path:string;query:string}){if(!line)return null;const parts=syntaxParts(line.text,path);return <>{parts.map((part,index)=><span key={index} className={part.kind?`syntax-${part.kind}`:query&&part.text.toLowerCase().includes(query.toLowerCase())?'diff-query-match':undefined}>{part.text}</span>)}</>}

export function splitRows(lines:DiffLine[]){const rows:Array<{left?:DiffLine;right?:DiffLine}>=[];for(let index=0;index<lines.length;index++){const line=lines[index];if(line.kind==='remove'){const next=lines[index+1];if(next?.kind==='add'){rows.push({left:line,right:next});index++;}else rows.push({left:line});}else if(line.kind==='add')rows.push({right:line});else rows.push({left:line,right:line});}return rows;}

export function statusMark(file:DiffFile){return file.binary?<FileImage size={11}/>:file.status==='renamed'||file.status==='copied'?<GitCompare size={11}/>:<span className={`diff-status diff-status--${file.status}`}>{file.status[0].toUpperCase()}</span>}

export function ImageDiff({file,data,repository,mode}:{file:DiffFile;data:DiffData;repository:string;mode:'live'|'demo'}){const[urls,setUrls]=useState<{before?:string;after?:string}>({});const[error,setError]=useState('');useEffect(()=>{let live=true;const created:string[]=[];(async()=>{try{if(mode==='demo')throw new Error('Image comparison is unavailable in the deterministic fixture.');const[owner,name]=repository.split('/');const load=async(reference:string|undefined,path:string)=>{if(!reference)return;const value=await invoke<RepositoryFile>('get_repo_file_content',{owner,name,expression:`${reference}:${path}`,path});if(!value.contentBase64)return;const url=createSafeImageUrl(value);created.push(url);return url;};const before=file.status==='added'?undefined:await load(data.baseRefName,file.oldPath);const after=file.status==='deleted'?undefined:await load(data.headRefName,file.newPath);if(live)setUrls({before,after});}catch(cause){if(live)setError(String(cause));}})();return()=>{live=false;for(const url of created)URL.revokeObjectURL(url)}},[data.baseRefName,data.headRefName,file,mode,repository]);if(error)return <div className="diff-state"><strong>Image comparison unavailable</strong><span>{error}</span></div>;return <div className="diff-image-compare"><figure><figcaption>Before</figcaption>{urls.before?<img src={urls.before} alt={`Before ${file.oldPath}`}/>:<span>Not present</span>}</figure><figure><figcaption>After</figcaption>{urls.after?<img src={urls.after} alt={`After ${file.newPath}`}/>:<span>Not present</span>}</figure></div>}

export function readableDiffError(value:string){const lower=value.toLowerCase();if(lower.includes('401')||lower.includes('auth'))return'GitHub authentication expired. Reconnect and retry.';if(lower.includes('403')||lower.includes('rate'))return'GitHub denied this request or the rate limit was reached.';if(lower.includes('404'))return'This data is unavailable or you no longer have permission.';return value.replace(/^Error:\s*/,'');}
