import { useEffect, useMemo, useRef, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { Check, ExternalLink, Files, Folder, GitPullRequest, Network, Rows3, Search } from 'lucide-react';
import { useModeStore } from '../../stores/mode-store';
import { useTabsStore } from '../../stores/tabs-store';
import { parseUnifiedDiff, type DiffFile } from '../../diff/diff-utils';
import { DiffFileView, readableDiffError, CHUNK, statusMark } from './DiffShared';
import { architectureContextEnabled } from '../../architecture/feature';
import { analyzePullRequestArchitecture } from '../../architecture/analyze';
import { useArchitectureStore } from '../../architecture/architecture-store';
import { useLayoutStore } from '../../stores/layout-store';
import { ArchitectureContext } from '../architecture/ArchitectureContext';
import { useRepositoryArchitecture } from '../../architecture/useRepositoryArchitecture';
import { usePullRequestDetails } from '../../hooks/usePullRequestDetails';
import { useArchitectureRefreshStore } from '../../architecture/refresh-state';
import './PullRequestDiff.css';

interface PersistedDiff { activePath:string; layout:'unified'|'split'; viewed:string[]; ignoreWhitespace:boolean; surface:'changes'|'architecture' }
const persistedKey=(repository:string,number:number)=>`snow-devil-diff:${repository}#${number}`;
function readPersisted(repository:string,number:number):PersistedDiff{try{return{activePath:'',layout:'unified',viewed:[],ignoreWhitespace:false,surface:'changes',...JSON.parse(localStorage.getItem(persistedKey(repository,number))??'{}')}}catch{return{activePath:'',layout:'unified',viewed:[],ignoreWhitespace:false,surface:'changes'}}}

export function PullRequestDiff({repository,number,observedHeadSha}:{repository:string;number:number;observedHeadSha?:string}){
  const mode=useModeStore(s=>s.mode);const name=repository.split('/')[1]??repository;const initial=useMemo(()=>readPersisted(repository,number),[repository,number]);const details=usePullRequestDetails(repository,number,observedHeadSha);const data=details.data;const error=details.error?String(details.error):undefined;const[surface,setSurface]=useState<'changes'|'architecture'>(architectureContextEnabled()?initial.surface:'changes');const[layout,setLayout]=useState<'unified'|'split'>(initial.layout);const[activePath,setActivePath]=useState(initial.activePath);const[query,setQuery]=useState('');const[ignoreWhitespace,setIgnoreWhitespace]=useState(initial.ignoreWhitespace);const[expandedContext,setExpandedContext]=useState(false);const[renderLimit,setRenderLimit]=useState(CHUNK);const[viewed,setViewed]=useState(new Set(initial.viewed));const mainRef=useRef<HTMLElement>(null);const activeTabId=useTabsStore(s=>s.activeTabId);const setInspectorOpen=useLayoutStore(s=>s.setInspectorOpen);const architectureEnabled=architectureContextEnabled();
  const completedHeadRef=useRef<string | undefined>(undefined);
  const setRefreshState=useArchitectureRefreshStore(s=>s.set);
  useEffect(()=>{if(!architectureEnabled)return;const currentHead=data?.headRefOid;const newHeadPending=Boolean(observedHeadSha&&currentHead&&currentHead!==observedHeadSha);if(details.isFetching&&newHeadPending){setRefreshState(activeTabId,{status:'syncing',headSha:observedHeadSha});return;}if(!details.isFetching&&currentHead&&completedHeadRef.current&&completedHeadRef.current!==currentHead){setRefreshState(activeTabId,{status:'updated',headSha:currentHead});const timer=window.setTimeout(()=>setRefreshState(activeTabId,{status:'current',headSha:currentHead}),4000);return()=>window.clearTimeout(timer);}if(currentHead)completedHeadRef.current=currentHead;},[activeTabId,architectureEnabled,data?.headRefOid,details.isFetching,observedHeadSha,setRefreshState]);
  useEffect(()=>{if(!architectureEnabled||!observedHeadSha||!data?.headRefOid||data.headRefOid===observedHeadSha||!details.isFetching)return;const timer=window.setTimeout(()=>{setRefreshState(activeTabId,{status:'current',headSha:data.headRefOid});void details.refetch();},15000);return()=>window.clearTimeout(timer)},[activeTabId,architectureEnabled,data?.headRefOid,details.isFetching,details.refetch,observedHeadSha,setRefreshState]);
  useEffect(()=>{if(!architectureEnabled||!details.error||!data?.headRefOid)return;setRefreshState(activeTabId,{status:'current',headSha:data.headRefOid})},[activeTabId,architectureEnabled,data?.headRefOid,details.error,setRefreshState]);
  useEffect(()=>{localStorage.setItem(persistedKey(repository,number),JSON.stringify({activePath,layout,viewed:[...viewed],ignoreWhitespace,surface}));},[activePath,ignoreWhitespace,layout,number,repository,surface,viewed]);
  const files=useMemo(()=>parseUnifiedDiff(data?.diff??''),[data?.diff]);
  const repositoryArchitecture=useRepositoryArchitecture(repository,data?.baseRefOid,architectureEnabled&&Boolean(data)&&surface==='architecture');
  const architectureImpact=useMemo(()=>architectureEnabled&&surface==='architecture'&&data&&(!repositoryArchitecture.isLoading)?analyzePullRequestArchitecture({repositoryId:repository,pullRequestNumber:number,baseSha:data.baseRefOid,headSha:data.headRefOid,decisionContext:data.architectureDecisionContext,snapshot:repositoryArchitecture.data,files:files.map(file=>({oldPath:file.oldPath,newPath:file.newPath,status:file.status==='added'||file.status==='deleted'||file.status==='renamed'?file.status:'modified',additions:file.additions,deletions:file.deletions,lines:file.lines.map(line=>({type:line.kind,text:line.text}))}))}):undefined,[architectureEnabled,data,files,number,repository,repositoryArchitecture.data,repositoryArchitecture.isLoading,surface]);
  useEffect(()=>{useArchitectureStore.getState().setImpact(activeTabId,architectureImpact)},[activeTabId,architectureImpact]);
  useEffect(()=>{if(!architectureImpact||!(window as unknown as {__TAURI_INTERNALS__?:unknown}).__TAURI_INTERNALS__)return;const common={repositoryId:architectureImpact.repositoryId,algorithmVersion:architectureImpact.snapshot.algorithmVersion,generatedAt:architectureImpact.generatedAt};void invoke('save_pr_architecture_impact',{...common,pullRequestNumber:architectureImpact.pullRequestNumber,baseSha:architectureImpact.baseSha,headSha:architectureImpact.headSha,snapshotSha:architectureImpact.architectureSnapshotSha,payload:architectureImpact}).catch(error=>console.warn('[Architecture Context] Cache write failed',error));},[architectureImpact]);
  useEffect(()=>{if(activePath&&!files.some(file=>file.newPath===activePath))setActivePath('')},[activePath,files]);
  const selected=activePath?files.filter(file=>file.newPath===activePath):files;const matching=useMemo(()=>query.trim()?selected.filter(file=>file.newPath.toLowerCase().includes(query.toLowerCase())||file.lines.some(line=>line.text.toLowerCase().includes(query.toLowerCase()))):selected,[query,selected]);
  const groups=useMemo(()=>{const map=new Map<string,DiffFile[]>();for(const file of files){const folder=file.newPath.includes('/')?file.newPath.slice(0,file.newPath.lastIndexOf('/')):'Repository root';map.set(folder,[...(map.get(folder)??[]),file]);}return[...map.entries()]},[files]);
  const totals=files.reduce((sum,file)=>({additions:sum.additions+file.additions,deletions:sum.deletions+file.deletions}),{additions:0,deletions:0});
  const openGithub=()=>useTabsStore.getState().openBrowserTab(`github:pr:${repository}:${number}`,'pullRequest',`PR #${number}`,`https://github.com/${repository}/pull/${number}`,false,true);
  const selectFile=(path:string)=>{setActivePath(path);setRenderLimit(CHUNK);setExpandedContext(false);mainRef.current?.scrollTo({top:0})};
  const selectArchitectureComponent=(componentId:string)=>{useArchitectureStore.getState().selectComponent(activeTabId,componentId);setInspectorOpen(true)};
  const openArchitectureFile=(path:string)=>{selectFile(path);setSurface('changes')};
  const toggleViewed=(path:string)=>setViewed(current=>{const next=new Set(current);if(next.has(path))next.delete(path);else next.add(path);return next});
  const openOriginal=(file:DiffFile)=>useTabsStore.getState().openNativeTab(`native:repo:${repository}`,'repositoryExplorer',name,false,true,{type:'repository',repository,ref:data?.headRefName,path:file.newPath});

  return <div className="native-diff"><header className="native-diff__header"><div><span>{surface==='architecture'?'Pull request architecture':'Native pull request diff'}</span><h1><GitPullRequest size={18}/>{data?.title??`Pull request #${number}`}</h1><p>{repository} #{number}{data?` · ${data.state} · ${data.author?.login}`:''} · <b>+{totals.additions}</b> <i>-{totals.deletions}</i></p></div><div className="native-diff__actions"><div role="group" aria-label="Pull request sections"><button className={surface==='changes'?'is-active':''} onClick={()=>setSurface('changes')}><Files size={14}/>Changes</button>{architectureEnabled&&<button className={surface==='architecture'?'is-active':''} onClick={()=>setSurface('architecture')}><Network size={14}/>Architecture Context</button>}</div>{surface==='changes'&&<><label className="diff-search"><Search size={13}/><input aria-label="Search changed files" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search changes"/></label><button className={ignoreWhitespace?'is-active':''} aria-pressed={ignoreWhitespace} onClick={()=>setIgnoreWhitespace(value=>!value)}>Whitespace</button><div role="group" aria-label="Diff layout"><button className={layout==='unified'?'is-active':''} onClick={()=>setLayout('unified')}><Rows3 size={14}/>Unified</button><button className={layout==='split'?'is-active':''} onClick={()=>setLayout('split')}><Files size={14}/>Split</button></div></>}<button onClick={openGithub}><ExternalLink size={14}/>Open on GitHub</button></div></header>
    {error&&<div className="diff-state"><strong>Unable to load this pull request</strong><span>{readableDiffError(error)}</span></div>}{!data&&!error&&<div className="diff-state" style={{ display: 'flex', flex: 1, minHeight: 0, flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '24px' }}><div className="global-spinner" /><div style={{ textAlign: 'center' }}><h1 style={{ fontSize: '24px', fontWeight: 600, margin: 0, color: 'var(--text-primary)', animation: 'fresh-fade-in 0.5s ease-out' }}>Loading pull request changes…</h1></div></div>}{data&&surface==='architecture'&&repositoryArchitecture.isLoading&&<div className="diff-state" style={{ display: 'flex', flex: 1, minHeight: 0, flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '24px' }}><div className="global-spinner" /><div style={{ textAlign: 'center' }}><h1 style={{ fontSize: '24px', fontWeight: 600, margin: 0, color: 'var(--text-primary)', animation: 'fresh-fade-in 0.5s ease-out' }}>Building repository architecture</h1><p style={{ color: 'var(--text-muted)', fontSize: '15px', marginTop: '12px', animation: 'fresh-fade-in 0.7s ease-out backwards' }}>Fetching repository tree · discovering project boundaries · mapping dependencies and owners</p></div></div>}{data&&surface==='architecture'&&architectureImpact&&<ArchitectureContext impact={architectureImpact} onSelectComponent={selectArchitectureComponent} onOpenFile={openArchitectureFile}/>} {data&&surface==='changes'&&<div className="native-diff__body"><aside aria-label="Changed files"><header><strong>{files.length} changed files</strong><button onClick={()=>setActivePath('')}>All files</button></header>{groups.map(([folder,group])=><section className="diff-file-group" key={folder}><h3><Folder size={12}/>{folder}</h3>{group.map(file=><button className={file.newPath===activePath?'is-active':''} key={file.newPath} onClick={()=>selectFile(file.newPath)} data-tooltip={`${file.newPath}\nSelect to reveal this file's pull request changes.`}><span>{viewed.has(file.newPath)?<Check size={11}/>:statusMark(file)}{file.newPath.split('/').pop()}</span><small><b>+{file.additions}</b> <i>-{file.deletions}</i></small></button>)}</section>)}</aside><main ref={mainRef}>{matching.length===0?<div className="diff-state"><strong>{files.length?'No matching changes':'Empty diff'}</strong><span>{files.length?'Try a broader changed-file search.':'GitHub returned no textual or binary patch content.'}</span></div>:matching.map(file=><DiffFileView key={file.newPath} file={file} layout={layout} query={query} ignoreWhitespace={ignoreWhitespace} expandedContext={expandedContext} renderLimit={renderLimit} data={data} repository={repository} mode={mode} viewed={viewed.has(file.newPath)} onToggleViewed={()=>toggleViewed(file.newPath)} onExpandContext={()=>setExpandedContext(true)} onRenderMore={()=>setRenderLimit(value=>value+CHUNK)} onOpenOriginal={()=>openOriginal(file)}/>)}</main></div>}
  </div>;
}
