import { useEffect, useMemo, useRef, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { Check, ChevronDown, ExternalLink, Eye, EyeOff, FileImage, Files, Folder, GitCompare, GitPullRequest, Rows3, Search } from 'lucide-react';
import { useModeStore } from '../../stores/mode-store';
import { useTabsStore } from '../../stores/tabs-store';
import { demoPullRequest } from '../../repository/demo-repository';
import { collapseUnchanged, isWhitespaceOnlyChange, parseUnifiedDiff, syntaxParts, type DiffFile, type DiffLine } from '../../diff/diff-utils';
import type { RepositoryFile } from '../../repository/repository-types';
import { createSafeImageUrl } from '../../repository/image-preview';
import './PullRequestDiff.css';

const IMAGE=/\.(png|jpe?g|webp|svg)$/i;const CHUNK=1600;
interface PullRequestData extends Omit<typeof demoPullRequest,'baseRefName'|'headRefName'>{baseRefName?:string;headRefName?:string;diffTruncated?:boolean}
interface PersistedDiff { activePath:string; layout:'unified'|'split'; viewed:string[]; ignoreWhitespace:boolean }
const persistedKey=(repository:string,number:number)=>`snow-devil-diff:${repository}#${number}`;
function readPersisted(repository:string,number:number):PersistedDiff{try{return{activePath:'',layout:'unified',viewed:[],ignoreWhitespace:false,...JSON.parse(localStorage.getItem(persistedKey(repository,number))??'{}')}}catch{return{activePath:'',layout:'unified',viewed:[],ignoreWhitespace:false}}}

export function PullRequestDiff({repository,number}:{repository:string;number:number}){
  const mode=useModeStore(s=>s.mode);const[owner,name]=repository.split('/');const initial=useMemo(()=>readPersisted(repository,number),[repository,number]);const[data,setData]=useState<PullRequestData>();const[error,setError]=useState<string>();const[layout,setLayout]=useState<'unified'|'split'>(initial.layout);const[activePath,setActivePath]=useState(initial.activePath);const[query,setQuery]=useState('');const[ignoreWhitespace,setIgnoreWhitespace]=useState(initial.ignoreWhitespace);const[expandedContext,setExpandedContext]=useState(false);const[renderLimit,setRenderLimit]=useState(CHUNK);const[viewed,setViewed]=useState(new Set(initial.viewed));const mainRef=useRef<HTMLElement>(null);
  useEffect(()=>{let current=true;setData(undefined);setError(undefined);(mode==='demo'?Promise.resolve(demoPullRequest):invoke<PullRequestData>('get_pr_details',{owner,name,number})).then(value=>{if(current)setData(value)}).catch(cause=>{if(current)setError(String(cause))});return()=>{current=false}},[mode,name,number,owner]);
  useEffect(()=>{localStorage.setItem(persistedKey(repository,number),JSON.stringify({activePath,layout,viewed:[...viewed],ignoreWhitespace}));},[activePath,ignoreWhitespace,layout,number,repository,viewed]);
  const files=useMemo(()=>parseUnifiedDiff(data?.diff??''),[data?.diff]);
  useEffect(()=>{if(activePath&&!files.some(file=>file.newPath===activePath))setActivePath('')},[activePath,files]);
  const selected=activePath?files.filter(file=>file.newPath===activePath):files;const matching=useMemo(()=>query.trim()?selected.filter(file=>file.newPath.toLowerCase().includes(query.toLowerCase())||file.lines.some(line=>line.text.toLowerCase().includes(query.toLowerCase()))):selected,[query,selected]);
  const groups=useMemo(()=>{const map=new Map<string,DiffFile[]>();for(const file of files){const folder=file.newPath.includes('/')?file.newPath.slice(0,file.newPath.lastIndexOf('/')):'Repository root';map.set(folder,[...(map.get(folder)??[]),file]);}return[...map.entries()]},[files]);
  const totals=files.reduce((sum,file)=>({additions:sum.additions+file.additions,deletions:sum.deletions+file.deletions}),{additions:0,deletions:0});
  const openGithub=()=>useTabsStore.getState().openBrowserTab(`github:pr:${repository}:${number}`,'pullRequest',`PR #${number}`,`https://github.com/${repository}/pull/${number}`,false,true);
  const selectFile=(path:string)=>{setActivePath(path);setRenderLimit(CHUNK);setExpandedContext(false);mainRef.current?.scrollTo({top:0})};
  const toggleViewed=(path:string)=>setViewed(current=>{const next=new Set(current);if(next.has(path))next.delete(path);else next.add(path);return next});
  const openOriginal=(file:DiffFile)=>useTabsStore.getState().openNativeTab(`native:repo:${repository}`,'repositoryExplorer',name,false,true,{type:'repository',repository,ref:data?.headRefName,path:file.newPath});

  return <div className="native-diff"><header className="native-diff__header"><div><span>Native pull request diff</span><h1><GitPullRequest size={18}/>{data?.title??`Pull request #${number}`}</h1><p>{repository} #{number}{data?` · ${data.state} · ${data.author?.login}`:''} · <b>+{totals.additions}</b> <i>-{totals.deletions}</i></p></div><div className="native-diff__actions"><label className="diff-search"><Search size={13}/><input aria-label="Search changed files" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search changes"/></label><button className={ignoreWhitespace?'is-active':''} aria-pressed={ignoreWhitespace} onClick={()=>setIgnoreWhitespace(value=>!value)}>Whitespace</button><div role="group" aria-label="Diff layout"><button className={layout==='unified'?'is-active':''} onClick={()=>setLayout('unified')}><Rows3 size={14}/>Unified</button><button className={layout==='split'?'is-active':''} onClick={()=>setLayout('split')}><Files size={14}/>Split</button></div><button onClick={openGithub}><ExternalLink size={14}/>Open on GitHub</button></div></header>
    {error&&<div className="diff-state"><strong>Unable to load this diff</strong><span>{readableDiffError(error)}</span></div>}{!data&&!error&&<div className="diff-state">Loading pull request changes…</div>}{data&&<div className="native-diff__body"><aside aria-label="Changed files"><header><strong>{files.length} changed files</strong><button onClick={()=>setActivePath('')}>All files</button></header>{groups.map(([folder,group])=><section className="diff-file-group" key={folder}><h3><Folder size={12}/>{folder}</h3>{group.map(file=><button className={file.newPath===activePath?'is-active':''} key={file.newPath} onClick={()=>selectFile(file.newPath)} title={file.newPath}><span>{viewed.has(file.newPath)?<Check size={11}/>:statusMark(file)}{file.newPath.split('/').pop()}</span><small><b>+{file.additions}</b> <i>-{file.deletions}</i></small></button>)}</section>)}</aside><main ref={mainRef}>{matching.length===0?<div className="diff-state"><strong>{files.length?'No matching changes':'Empty diff'}</strong><span>{files.length?'Try a broader changed-file search.':'GitHub returned no textual or binary patch content.'}</span></div>:matching.map(file=><DiffFileView key={file.newPath} file={file} layout={layout} query={query} ignoreWhitespace={ignoreWhitespace} expandedContext={expandedContext} renderLimit={renderLimit} data={data} repository={repository} mode={mode} viewed={viewed.has(file.newPath)} onToggleViewed={()=>toggleViewed(file.newPath)} onExpandContext={()=>setExpandedContext(true)} onRenderMore={()=>setRenderLimit(value=>value+CHUNK)} onOpenOriginal={()=>openOriginal(file)}/>)}</main></div>}
  </div>;
}

function DiffFileView({file,layout,query,ignoreWhitespace,expandedContext,renderLimit,data,repository,mode,viewed,onToggleViewed,onExpandContext,onRenderMore,onOpenOriginal}:{file:DiffFile;layout:'unified'|'split';query:string;ignoreWhitespace:boolean;expandedContext:boolean;renderLimit:number;data:PullRequestData;repository:string;mode:'live'|'demo';viewed:boolean;onToggleViewed:()=>void;onExpandContext:()=>void;onRenderMore:()=>void;onOpenOriginal:()=>void}){
  let lines=collapseUnchanged(file.lines,expandedContext);if(ignoreWhitespace)lines=lines.filter((line,index)=>!isWhitespaceOnlyChange(line,lines[index+(line.kind==='remove'?1:-1)]));const limited=lines.slice(0,renderLimit);const image=file.binary&&IMAGE.test(file.newPath);
  return <section className="diff-file"><header><span><strong>{file.newPath}</strong>{file.status!=='modified'&&<em>{file.status}</em>}{file.similarity!=null&&<em>{file.similarity}% similar</em>}{file.generated&&<em>generated</em>}{file.vendored&&<em>vendored</em>}</span><div><button onClick={onOpenOriginal}>Open source</button><button onClick={onToggleViewed}>{viewed?<EyeOff size={12}/>:<Eye size={12}/>} {viewed?'Unview':'Viewed'}</button><b>+{file.additions}</b><i>-{file.deletions}</i></div></header>{image?<ImageDiff file={file} data={data} repository={repository} mode={mode}/>:file.binary?<div className="diff-state"><strong>Binary file changed</strong><span>The patch does not contain binary bytes. Open the changed file or GitHub for details.</span></div>:<>{layout==='unified'?<table className="diff-unified"><tbody>{limited.map((line,index)=><DiffRow key={index} line={line} path={file.newPath} query={query} onExpand={onExpandContext}/>)}</tbody></table>:<table className="diff-split"><tbody>{splitRows(limited).map((row,index)=><tr key={index}><td className={row.left?.kind?`is-${row.left.kind}`:''}><span>{row.left?.oldNumber??''}</span><code><HighlightedCode line={row.left} path={file.oldPath} query={query}/></code></td><td className={row.right?.kind?`is-${row.right.kind}`:''}><span>{row.right?.newNumber??''}</span><code><HighlightedCode line={row.right} path={file.newPath} query={query}/></code></td></tr>)}</tbody></table>}{limited.some(line=>line.collapsedCount)&&<button className="diff-expand-context" onClick={onExpandContext}><ChevronDown size={13}/>Expand unchanged context</button>}{lines.length>limited.length&&<button className="diff-load-more" onClick={onRenderMore}>Render {Math.min(CHUNK,lines.length-limited.length).toLocaleString()} more lines</button>}{data.diffTruncated&&<div className="diff-warning">GitHub truncated this patch. Open on GitHub for the complete change.</div>}</>}</section>;
}

function DiffRow({line,path,query,onExpand}:{line:DiffLine;path:string;query:string;onExpand:()=>void}){return <tr className={`is-${line.kind}`}><td>{line.oldNumber??''}</td><td>{line.newNumber??''}</td><td><code>{line.collapsedCount?<button className="diff-collapsed" onClick={onExpand}>{line.text}</button>:<><span>{line.kind==='add'?'+':line.kind==='remove'?'-':' '}</span><HighlightedCode line={line} path={path} query={query}/></>}</code></td></tr>}
function HighlightedCode({line,path,query}:{line?:DiffLine;path:string;query:string}){if(!line)return null;const parts=syntaxParts(line.text,path);return <>{parts.map((part,index)=><span key={index} className={part.kind?`syntax-${part.kind}`:query&&part.text.toLowerCase().includes(query.toLowerCase())?'diff-query-match':undefined}>{part.text}</span>)}</>}
function splitRows(lines:DiffLine[]){const rows:Array<{left?:DiffLine;right?:DiffLine}>=[];for(let index=0;index<lines.length;index++){const line=lines[index];if(line.kind==='remove'){const next=lines[index+1];if(next?.kind==='add'){rows.push({left:line,right:next});index++;}else rows.push({left:line});}else if(line.kind==='add')rows.push({right:line});else rows.push({left:line,right:line});}return rows;}
function statusMark(file:DiffFile){return file.binary?<FileImage size={11}/>:file.status==='renamed'||file.status==='copied'?<GitCompare size={11}/>:<span className={`diff-status diff-status--${file.status}`}>{file.status[0].toUpperCase()}</span>}

function ImageDiff({file,data,repository,mode}:{file:DiffFile;data:PullRequestData;repository:string;mode:'live'|'demo'}){const[urls,setUrls]=useState<{before?:string;after?:string}>({});const[error,setError]=useState('');useEffect(()=>{let live=true;const created:string[]=[];(async()=>{try{if(mode==='demo')throw new Error('Image comparison is unavailable in the deterministic fixture.');const[owner,name]=repository.split('/');const load=async(reference:string|undefined,path:string)=>{if(!reference)return;const value=await invoke<RepositoryFile>('get_repo_file_content',{owner,name,expression:`${reference}:${path}`,path});if(!value.contentBase64)return;const url=createSafeImageUrl(value);created.push(url);return url;};const before=file.status==='added'?undefined:await load(data.baseRefName,file.oldPath);const after=file.status==='deleted'?undefined:await load(data.headRefName,file.newPath);if(live)setUrls({before,after});}catch(cause){if(live)setError(String(cause));}})();return()=>{live=false;for(const url of created)URL.revokeObjectURL(url)}},[data.baseRefName,data.headRefName,file,mode,repository]);if(error)return <div className="diff-state"><strong>Image comparison unavailable</strong><span>{error}</span></div>;return <div className="diff-image-compare"><figure><figcaption>Before</figcaption>{urls.before?<img src={urls.before} alt={`Before ${file.oldPath}`}/>:<span>Not present</span>}</figure><figure><figcaption>After</figcaption>{urls.after?<img src={urls.after} alt={`After ${file.newPath}`}/>:<span>Not present</span>}</figure></div>}
function readableDiffError(value:string){const lower=value.toLowerCase();if(lower.includes('401')||lower.includes('auth'))return'GitHub authentication expired. Reconnect and retry.';if(lower.includes('403')||lower.includes('rate'))return'GitHub denied this request or the rate limit was reached.';if(lower.includes('404'))return'This pull request is unavailable or you no longer have permission.';return value.replace(/^Error:\s*/,'');}
